// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkWhnQMFTbTL5ygi5B28ge7CAkM1KS8WE',
    appId: '1:417396696005:web:d7daf356a187f69260a1ac',
    messagingSenderId: '417396696005',
    projectId: 'chat-app-58459',
    authDomain: 'chat-app-58459.firebaseapp.com',
    storageBucket: 'chat-app-58459.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUgSFUh9h143LoGnfgaIh888405WIzS3U',
    appId: '1:417396696005:android:7378e5bf00152a9a60a1ac',
    messagingSenderId: '417396696005',
    projectId: 'chat-app-58459',
    storageBucket: 'chat-app-58459.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU8cDu5HBFY-dQsxphsuLxN-dayDoGbN4',
    appId: '1:417396696005:ios:07e13d83fae4f93460a1ac',
    messagingSenderId: '417396696005',
    projectId: 'chat-app-58459',
    storageBucket: 'chat-app-58459.appspot.com',
    iosClientId: '417396696005-6ibgosr32eif4p17s2l1cuvu93tvg29u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU8cDu5HBFY-dQsxphsuLxN-dayDoGbN4',
    appId: '1:417396696005:ios:07e13d83fae4f93460a1ac',
    messagingSenderId: '417396696005',
    projectId: 'chat-app-58459',
    storageBucket: 'chat-app-58459.appspot.com',
    iosClientId: '417396696005-6ibgosr32eif4p17s2l1cuvu93tvg29u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkWhnQMFTbTL5ygi5B28ge7CAkM1KS8WE',
    appId: '1:417396696005:web:952ac1bec22a752960a1ac',
    messagingSenderId: '417396696005',
    projectId: 'chat-app-58459',
    authDomain: 'chat-app-58459.firebaseapp.com',
    storageBucket: 'chat-app-58459.appspot.com',
  );
}
